version: '3.8'

services:
  querygenie:
    build: .
    container_name: querygenie-rag
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - TRANSFORMERS_CACHE=/app/.cache/transformers
      - HF_HOME=/app/.cache/huggingface
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - querygenie-network

  # Optional: Add a simple web interface
  web-interface:
    image: nginx:alpine
    container_name: querygenie-web
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
    depends_on:
      - querygenie
    restart: unless-stopped
    networks:
      - querygenie-network

networks:
  querygenie-network:
    driver: bridge

volumes:
  data:
    driver: local
  logs:
    driver: local
